global using CommunityToolkit.Maui;
global using HVAC_APP_3.Views;
global using System.Collections.ObjectModel;
global using System.ComponentModel;
global using System.Diagnostics;
global using System.Globalization;
global using System.Runtime.CompilerServices;
global using System.Text.Json;
global using System.Threading.Tasks;
